blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://walletgate.app/docs
    about: Check our documentation for SDK usage and examples
  - name: Community Support
    url: https://github.com/walletgate/eudi-sdk/discussions
    about: Ask questions and discuss with the community
  - name: Security Issues
    url: mailto:security@walletgate.app
    about: Please report security vulnerabilities directly via email